"""initial provenance core (14 tables)

Revision ID: 8a6a416af425
Revises:
Create Date: 2026-08-15 11:44:17.065054

"""

from __future__ import annotations

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision = "8a6a416af425"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "kv_cache",
        sa.Column("key", sa.String(length=128), nullable=False),
        sa.Column("model", sa.String(length=128), nullable=False),
        sa.Column("prompt_hash", sa.String(length=64), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("key", name=op.f("pk_kv_cache")),
    )
    op.create_index("ix_kv_cache_expires_at", "kv_cache", ["expires_at"], unique=False)
    op.create_table(
        "tenants",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("namespace", sa.String(length=64), nullable=False),
        sa.Column("rbac_policy", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tenants")),
        sa.UniqueConstraint("namespace", name=op.f("uq_tenants_namespace")),
    )
    op.create_table(
        "runs",
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("question", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("stage", sa.String(length=64), nullable=True),
        sa.Column("progress", sa.Float(), nullable=False),
        sa.Column("cost_budget_usd", sa.Numeric(precision=12, scale=4), nullable=False),
        sa.Column("cost_spent_usd", sa.Numeric(precision=12, scale=4), nullable=False),
        sa.Column("checkpoint", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "status IN ('submitted','planning','searching','collecting','storing','extracting','comparing','verifying','detecting','concluding','tracing','completed','failed','paused','cancelled')",
            name=op.f("ck_runs_valid_run_status"),
        ),
        sa.CheckConstraint("cost_spent_usd >= 0.0", name=op.f("ck_runs_non_negative_cost")),
        sa.CheckConstraint(
            "progress >= 0.0 AND progress <= 1.0", name=op.f("ck_runs_valid_progress")
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_runs_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_runs")),
    )
    op.create_index("ix_runs_tenant_created", "runs", ["tenant_id", "created_at"], unique=False)
    op.create_index("ix_runs_tenant_status", "runs", ["tenant_id", "status"], unique=False)
    op.create_table(
        "audit_trace",
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("entity_type", sa.String(length=64), nullable=False),
        sa.Column("entity_id", sa.String(length=64), nullable=True),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("actor", sa.String(length=64), nullable=True),
        sa.Column("decision", sa.String(length=64), nullable=True),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("evidence", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "ts", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"], ["runs.id"], name=op.f("fk_audit_trace_run_id_runs"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_trace")),
    )
    op.create_index(
        "ix_audit_trace_entity", "audit_trace", ["entity_type", "entity_id"], unique=False
    )
    op.create_index("ix_audit_trace_run_id", "audit_trace", ["run_id"], unique=False)
    op.create_index("ix_audit_trace_ts", "audit_trace", ["ts"], unique=False)
    op.create_table(
        "checkpoints",
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("stage", sa.String(length=64), nullable=False),
        sa.Column("state", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "ts", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"], ["runs.id"], name=op.f("fk_checkpoints_run_id_runs"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_checkpoints")),
        sa.UniqueConstraint("run_id", "stage", name="uq_checkpoints_run_stage"),
    )
    op.create_table(
        "conclusions",
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("human_review_required", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "confidence IS NULL OR (confidence >= 0.0 AND confidence <= 1.0)",
            name=op.f("ck_conclusions_valid_confidence"),
        ),
        sa.ForeignKeyConstraint(
            ["run_id"], ["runs.id"], name=op.f("fk_conclusions_run_id_runs"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_conclusions")),
    )
    op.create_index("ix_conclusions_run_id", "conclusions", ["run_id"], unique=False)
    op.create_table(
        "findings",
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=512), nullable=False),
        sa.Column("evidence_tier", sa.String(length=16), nullable=True),
        sa.Column("domain_tags", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("stance", sa.String(length=64), nullable=True),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "evidence_tier IN ('t1','t2','t3','t4')", name=op.f("ck_findings_valid_evidence_tier")
        ),
        sa.CheckConstraint(
            "confidence IS NULL OR (confidence >= 0.0 AND confidence <= 1.0)",
            name=op.f("ck_findings_valid_confidence"),
        ),
        sa.ForeignKeyConstraint(
            ["run_id"], ["runs.id"], name=op.f("fk_findings_run_id_runs"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_findings")),
    )
    op.create_index("ix_findings_run_id", "findings", ["run_id"], unique=False)
    op.create_table(
        "sources",
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("uri", sa.Text(), nullable=False),
        sa.Column("title", sa.String(length=1024), nullable=True),
        sa.Column("source_type", sa.String(length=32), nullable=False),
        sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("raw_ref", sa.String(length=512), nullable=True),
        sa.Column("allowlisted_uri", sa.Boolean(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "source_type IN ('web','pdf','rss','docx','rtf','upload','other')",
            name=op.f("ck_sources_valid_source_type"),
        ),
        sa.CheckConstraint(
            "status IN ('pending','fetched','failed','normalized','quarantined')",
            name=op.f("ck_sources_valid_source_status"),
        ),
        sa.ForeignKeyConstraint(
            ["run_id"], ["runs.id"], name=op.f("fk_sources_run_id_runs"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sources")),
        sa.UniqueConstraint("content_hash", name="uq_sources_content_hash"),
    )
    op.create_index("ix_sources_run_id", "sources", ["run_id"], unique=False)
    op.create_index("ix_sources_uri", "sources", ["uri"], unique=False)
    op.create_table(
        "passages",
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column("seq", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("start_char", sa.Integer(), nullable=True),
        sa.Column("end_char", sa.Integer(), nullable=True),
        sa.Column("hash", sa.String(length=64), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["sources.id"],
            name=op.f("fk_passages_source_id_sources"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_passages")),
        sa.UniqueConstraint("source_id", "seq", name="uq_passages_source_seq"),
    )
    op.create_index("ix_passages_hash", "passages", ["hash"], unique=False)
    op.create_index("ix_passages_source_id", "passages", ["source_id"], unique=False)
    op.create_table(
        "statements",
        sa.Column("passage_id", sa.Uuid(), nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "status IN ('draft','verified','quarantined')",
            name=op.f("ck_statements_valid_statement_status"),
        ),
        sa.CheckConstraint(
            "confidence IS NULL OR (confidence >= 0.0 AND confidence <= 1.0)",
            name=op.f("ck_statements_valid_confidence"),
        ),
        sa.ForeignKeyConstraint(
            ["passage_id"],
            ["passages.id"],
            name=op.f("fk_statements_passage_id_passages"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["run_id"], ["runs.id"], name=op.f("fk_statements_run_id_runs"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_statements")),
    )
    op.create_index("ix_statements_passage_id", "statements", ["passage_id"], unique=False)
    op.create_index("ix_statements_run_id", "statements", ["run_id"], unique=False)
    op.create_index("ix_statements_run_status", "statements", ["run_id", "status"], unique=False)
    op.create_index("ix_statements_status", "statements", ["status"], unique=False)
    op.create_table(
        "conclusion_evidence",
        sa.Column("conclusion_id", sa.Uuid(), nullable=False),
        sa.Column("statement_id", sa.Uuid(), nullable=False),
        sa.Column("finding_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["conclusion_id"],
            ["conclusions.id"],
            name=op.f("fk_conclusion_evidence_conclusion_id_conclusions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["finding_id"],
            ["findings.id"],
            name=op.f("fk_conclusion_evidence_finding_id_findings"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["statement_id"],
            ["statements.id"],
            name=op.f("fk_conclusion_evidence_statement_id_statements"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint(
            "conclusion_id", "statement_id", name=op.f("pk_conclusion_evidence")
        ),
    )
    op.create_index(
        "ix_conclusion_evidence_statement_id", "conclusion_evidence", ["statement_id"], unique=False
    )
    op.create_table(
        "contradictions",
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("statement_a_id", sa.Uuid(), nullable=False),
        sa.Column("statement_b_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("evidence", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "status IN ('flagged','confirmed','rejected')",
            name=op.f("ck_contradictions_valid_contradiction_status"),
        ),
        sa.ForeignKeyConstraint(
            ["run_id"], ["runs.id"], name=op.f("fk_contradictions_run_id_runs"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["statement_a_id"],
            ["statements.id"],
            name=op.f("fk_contradictions_statement_a_id_statements"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["statement_b_id"],
            ["statements.id"],
            name=op.f("fk_contradictions_statement_b_id_statements"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_contradictions")),
    )
    op.create_index("ix_contradictions_run_id", "contradictions", ["run_id"], unique=False)
    op.create_index("ix_contradictions_status", "contradictions", ["status"], unique=False)
    op.create_index("ix_contradictions_stmt_a", "contradictions", ["statement_a_id"], unique=False)
    op.create_index("ix_contradictions_stmt_b", "contradictions", ["statement_b_id"], unique=False)
    op.create_table(
        "evidence_links",
        sa.Column("statement_id", sa.Uuid(), nullable=False),
        sa.Column("passage_id", sa.Uuid(), nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("score", sa.String(length=16), nullable=False),
        sa.Column("method", sa.String(length=64), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "score IN ('full','partial','none')",
            name=op.f("ck_evidence_links_valid_evidence_score"),
        ),
        sa.ForeignKeyConstraint(
            ["passage_id"],
            ["passages.id"],
            name=op.f("fk_evidence_links_passage_id_passages"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["run_id"], ["runs.id"], name=op.f("fk_evidence_links_run_id_runs"), ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["statement_id"],
            ["statements.id"],
            name=op.f("fk_evidence_links_statement_id_statements"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_evidence_links")),
    )
    op.create_index("ix_evidence_links_passage_id", "evidence_links", ["passage_id"], unique=False)
    op.create_index("ix_evidence_links_run_id", "evidence_links", ["run_id"], unique=False)
    op.create_index(
        "ix_evidence_links_statement_id", "evidence_links", ["statement_id"], unique=False
    )
    op.create_table(
        "finding_statements",
        sa.Column("finding_id", sa.Uuid(), nullable=False),
        sa.Column("statement_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["finding_id"],
            ["findings.id"],
            name=op.f("fk_finding_statements_finding_id_findings"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["statement_id"],
            ["statements.id"],
            name=op.f("fk_finding_statements_statement_id_statements"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("finding_id", "statement_id", name=op.f("pk_finding_statements")),
    )
    op.create_index(
        "ix_finding_statements_statement_id", "finding_statements", ["statement_id"], unique=False
    )
    # ### end Alembic commands ###

    # Append-only enforcement — defense in depth (ORM listeners live in app.db.base).
    # UPDATE/DELETE on evidence_links and audit_trace is impossible at the DB level.
    op.execute(
        """
        CREATE FUNCTION trg_append_only_no_update_delete() RETURNS trigger AS $$
        BEGIN
            RAISE EXCEPTION 'append-only table: % UPDATE/DELETE forbidden', TG_TABLE_NAME
                USING ERRCODE = 'restrict_violation';
        END;
        $$ LANGUAGE plpgsql
        """
    )
    for table in ("evidence_links", "audit_trace"):
        op.execute(
            f"CREATE TRIGGER trg_{table}_append_only "
            f"BEFORE UPDATE OR DELETE ON {table} FOR EACH ROW "
            "EXECUTE FUNCTION trg_append_only_no_update_delete();"
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TRIGGER IF EXISTS trg_audit_trace_append_only ON audit_trace;")
    op.execute("DROP TRIGGER IF EXISTS trg_evidence_links_append_only ON evidence_links;")
    op.execute("DROP FUNCTION IF EXISTS trg_append_only_no_update_delete();")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_finding_statements_statement_id", table_name="finding_statements")
    op.drop_table("finding_statements")
    op.drop_index("ix_evidence_links_statement_id", table_name="evidence_links")
    op.drop_index("ix_evidence_links_run_id", table_name="evidence_links")
    op.drop_index("ix_evidence_links_passage_id", table_name="evidence_links")
    op.drop_table("evidence_links")
    op.drop_index("ix_contradictions_stmt_b", table_name="contradictions")
    op.drop_index("ix_contradictions_stmt_a", table_name="contradictions")
    op.drop_index("ix_contradictions_status", table_name="contradictions")
    op.drop_index("ix_contradictions_run_id", table_name="contradictions")
    op.drop_table("contradictions")
    op.drop_index("ix_conclusion_evidence_statement_id", table_name="conclusion_evidence")
    op.drop_table("conclusion_evidence")
    op.drop_index("ix_statements_status", table_name="statements")
    op.drop_index("ix_statements_run_status", table_name="statements")
    op.drop_index("ix_statements_run_id", table_name="statements")
    op.drop_index("ix_statements_passage_id", table_name="statements")
    op.drop_table("statements")
    op.drop_index("ix_passages_source_id", table_name="passages")
    op.drop_index("ix_passages_hash", table_name="passages")
    op.drop_table("passages")
    op.drop_index("ix_sources_uri", table_name="sources")
    op.drop_index("ix_sources_run_id", table_name="sources")
    op.drop_table("sources")
    op.drop_index("ix_findings_run_id", table_name="findings")
    op.drop_table("findings")
    op.drop_index("ix_conclusions_run_id", table_name="conclusions")
    op.drop_table("conclusions")
    op.drop_table("checkpoints")
    op.drop_index("ix_audit_trace_ts", table_name="audit_trace")
    op.drop_index("ix_audit_trace_run_id", table_name="audit_trace")
    op.drop_index("ix_audit_trace_entity", table_name="audit_trace")
    op.drop_table("audit_trace")
    op.drop_index("ix_runs_tenant_status", table_name="runs")
    op.drop_index("ix_runs_tenant_created", table_name="runs")
    op.drop_table("runs")
    op.drop_table("tenants")
    op.drop_index("ix_kv_cache_expires_at", table_name="kv_cache")
    op.drop_table("kv_cache")
    # ### end Alembic commands ###
