"""change source content_hash unique to per-run

Revision ID: e3b4b1c57819
Revises: 5f2e3a8c9b1d
Create Date: 2026-08-17 11:46:52.830593

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = 'e3b4b1c57819'
down_revision = '5f2e3a8c9b1d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_sources_content_hash'), 'sources', type_='unique')
    op.create_unique_constraint('uq_sources_run_content_hash', 'sources', ['run_id', 'content_hash'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_sources_run_content_hash', 'sources', type_='unique')
    op.create_unique_constraint(op.f('uq_sources_content_hash'), 'sources', ['content_hash'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
