#!/usr/bin/env python3
"""Generate ``docs/licenses.md`` — the model & library inventory (task_015).

Pure-stdlib implementation (Python 3.12+): reads the *installed* distributions
via :mod:`importlib.metadata`, classifies each against the dependencies declared
in ``pyproject.toml`` (read via :mod:`tomllib`), and renders the full ECRKE
license inventory document. No new dependencies are introduced; the document is
regenerated reproducibly:

    python scripts/generate_licenses.py

The table format mirrors ``pip-licenses`` (Name | Version | License) with a
``Role`` column added to distinguish runtime / dev / transitive packages. If a
distribution exposes no license metadata, the cell reads ``UNKNOWN`` — the
reader must verify it from the package's own metadata before any legal review.
"""

from __future__ import annotations

import importlib.metadata
import re
import sys
import tomllib
from collections.abc import Iterable
from datetime import UTC, datetime
from pathlib import Path

# Leading name token of a PEP 508 dependency specifier (stops at extras/version).
_NAME_TOKEN = re.compile(r"^[A-Za-z0-9._-]+")
# Long license strings (full license text in metadata) are truncated in the table.
_MAX_LICENSE_LEN = 80

ROOT = Path(__file__).resolve().parents[1]
PYPROJECT = ROOT / "pyproject.toml"
OUTPUT = ROOT / "docs" / "licenses.md"

# Static prose sections (not derivable from installed metadata). These are the
# same statements a human reviewer would write; keeping them in the generator
# means the document regenerates as one unit.
DOC_HEADER = """# ECRKE — Model & Library Inventory with Licenses

| Field | Value |
|---|---|
| **Document** | Submission-pack artifact 5 (build-plan §2): model & library inventory with licenses |
| **Generated by** | `scripts/generate_licenses.py` (stdlib `importlib.metadata` — no new dependencies) |
| **Scope** | Python runtime deps, dev deps, full installed inventory, LLM provider terms, UI/fonts, sample data |
| **Reproduce** | `.venv\\Scripts\\python.exe scripts\\generate_licenses.py` (exit 0) |

---

## 1. Method

The inventory below is generated from the **actual installed distributions** in
this environment (`importlib.metadata.distributions()`), classified against the
dependencies declared in `pyproject.toml`:

| Role | Meaning |
|---|---|
| **runtime** | Declared in `[project].dependencies` — required to run the application |
| **dev** | Declared in `[project.optional-dependencies].dev` — required to develop/test |
| **transitive** | Installed as a dependency of a runtime/dev package (not declared directly) |
| **project** | The ECRKE package itself (`ecrke`, editable install) |

License metadata is read from each distribution's metadata in this order:
`License-Expression` (PEP 639), the `License` field, then `License :: OSI Approved ::
...` classifiers; otherwise the cell reads `UNKNOWN` and must be verified from
the package's own metadata. Long license texts are truncated to 80 characters in
the table (full text lives in each package's metadata). The table format mirrors
`pip-licenses` (Name | Version | License) with a `Role` column appended.
"""

DOC_PROVIDER_TERMS = """## 5. LLM Provider Terms (service terms, not software licenses)

ECRKE calls hosted LLM APIs through the LiteLLM gateway (`app/services/llm_gateway.py`).
The model **software licenses** of the underlying frameworks are listed above; the
**API terms** that govern usage of hosted models are the providers' then-current
service terms, summarized one line each (per design/tech-stack docs — exact terms
live on the provider sites; keys are referenced by env-var NAME only, Rule 01):

| Provider | API terms (one-line summary) |
|---|---|
| **OpenAI** (default through `OPENAI_API_KEY` via LiteLLM) | Hosted API service; customer retains rights to outputs, subject to OpenAI's then-current API/service terms; no training on your API data by default per OpenAI's enterprise terms. |
| **Anthropic** (`ANTHROPIC_API_KEY` via LiteLLM) | Hosted API service; customer owns outputs, subject to Anthropic's then-current Commercial Terms; input/output not used to train models per default commercial terms. |
| **Google** — Gemini (`GEMINI_API_KEY` via LiteLLM) | Hosted API service via Google AI Studio / Vertex AI; subject to Google's then-current Generative AI API terms; usage governed by Google Cloud or AI Studio terms depending on endpoint. |
| **Local / Ollama** (optional `local` extra) | Self-hosted open-weight models; governed by each model's license (e.g. Gemma, Llama community licenses) — no external API terms. |

ECRKE is **provider-agnostic** (LiteLLM): adding or swapping a provider is
configuration, not code. No provider key value is ever stored in the repository
(see `.env.example` for the variable NAMES).
"""

DOC_UI_FONTS = """## 6. UI / Icons / Fonts

| Asset | License note |
|---|---|
| **Grafana dashboard** (`grafana/dashboard.json`) | Grafana is an Apache-2.0-licensed project; the dashboard **JSON is our own data file** (ECRKE's panels/queries), not Grafana's code. No bundled icons or fonts ship in this repository. |
| **Prometheus config** (`prometheus/prometheus.yml`) | Prometheus is Apache-2.0-licensed; the YAML is our own configuration data file. |
| **Docker images** (`Dockerfile`, `docker-compose.yml`) | Base images (postgres, prefect, prometheus, grafana) are referenced by tag from their upstream registries and governed by each project's license (PostgreSQL License / Apache-2.0 / MIT as applicable). No third-party icons or fonts are bundled. |
"""

DOC_SAMPLE_DATA = """## 7. Sample Data

All files in `sample_data/` (RSS feed, HTML/TXT report, generated PDF, passages,
`seeds.jsonl`) are **synthetic** — generated by `scripts/generate_sample_data.py`
and the eval harness. They contain no copyrighted content, no real personal data,
and no proprietary text; they exist solely to demonstrate the pipeline and to
seed the gold eval set.

---

*Inventory generated by `scripts/generate_licenses.py` at {ts}.*
*Python: {python}.*
*Exit status of generator: 0 (this document exists because it ran).*
"""


def normalize(name: str) -> str:
    """Normalize a package name for comparison (PEP 503: casefold, strip -_ )."""
    return name.replace("_", "").replace("-", "").casefold()


def declared_names(entries: Iterable[str]) -> set[str]:
    """Extract base distribution names from dependency specifiers."""
    names: set[str] = set()
    for entry in entries:
        match = _NAME_TOKEN.match(entry.strip())
        if match:
            names.add(normalize(match.group(0)))
    return names


def dist_license(dist: importlib.metadata.Distribution) -> str:
    """Best-effort license string from a distribution's metadata."""
    meta = dist.metadata
    expression = meta.get("License-Expression")
    if expression:
        return _truncate(expression)
    license_field = (meta.get("License") or "").strip()
    if license_field and license_field.upper() != "UNKNOWN":
        return _truncate(license_field)
    classifiers = meta.get_all("Classifier") or []
    for classifier in classifiers:
        if classifier.startswith("License :: OSI Approved ::"):
            return _truncate(classifier.rsplit("::", 1)[-1].strip())
    for classifier in classifiers:
        if classifier.startswith("License ::"):
            return _truncate(classifier.rsplit("::", 1)[-1].strip())
    return "UNKNOWN"


def _truncate(value: str) -> str:
    """Truncate long license texts for a readable table cell."""
    compact = " ".join(value.split())
    if len(compact) <= _MAX_LICENSE_LEN:
        return compact
    return compact[:_MAX_LICENSE_LEN].rstrip() + " … (truncated)"


def render_table(rows: list[tuple[str, str, str, str]]) -> str:
    """Render a Name | Version | License | Role markdown table."""
    lines = ["| Name | Version | License | Role |", "|---|---|---|---|"]
    for name, version, license_, role in rows:
        safe = license_.replace("|", "\\|").replace("\n", " ")
        lines.append(f"| {name} | {version} | {safe} | {role} |")
    return "\n".join(lines)


def main() -> int:
    """Generate ``docs/licenses.md`` from installed metadata; exit 0 on success."""
    with PYPROJECT.open("rb") as handle:
        project = tomllib.load(handle)
    runtime_declared = declared_names(project["project"]["dependencies"])
    dev_declared = declared_names(project["project"]["optional-dependencies"]["dev"])

    dists = sorted(
        importlib.metadata.distributions(), key=lambda d: (d.metadata["Name"] or "").casefold()
    )

    runtime_rows: list[tuple[str, str, str, str]] = []
    dev_rows: list[tuple[str, str, str, str]] = []
    transitive_rows: list[tuple[str, str, str, str]] = []
    for dist in dists:
        name = dist.metadata["Name"] or "?"
        version = dist.version or "?"
        license_ = dist_license(dist)
        key = normalize(name)
        if key == normalize("ecrke"):
            continue  # the project itself, noted in the header
        if key in runtime_declared:
            role = "runtime"
            runtime_rows.append((name, version, license_, role))
        elif key in dev_declared:
            role = "dev"
            dev_rows.append((name, version, license_, role))
        else:
            role = "transitive"
            transitive_rows.append((name, version, license_, role))

    missing = sorted(
        normalize(name)
        for name in (runtime_declared | dev_declared)
        if name not in {normalize(d.metadata["Name"] or "") for d in dists}
    )

    ts = datetime.now(UTC).strftime("%Y-%m-%dT%H:%M:%SZ")
    parts = [
        DOC_HEADER,
        "## 2. Python Runtime Dependencies (installed)\n",
        render_table(runtime_rows),
        "\n## 3. Python Dev Dependencies (installed)\n",
        render_table(dev_rows),
        "\n## 4. Full Installed Inventory (incl. transitive)\n",
        render_table(transitive_rows),
        "",
        DOC_PROVIDER_TERMS,
        DOC_UI_FONTS,
        DOC_SAMPLE_DATA.format(ts=ts, python=sys.version.split()[0]),
    ]
    if missing:
        parts.append(
            "\n> **Declared but not installed in this environment:** "
            + ", ".join(sorted(missing))
            + "\n"
        )
    OUTPUT.write_text("\n".join(parts), encoding="utf-8")
    return 0


if __name__ == "__main__":
    sys.exit(main())
